on: push

jobs:
  pnpm-build:
    name: pnpm build工作
    runs-on: windows-latest
    steps:
      -run: echo "Hello, world!"
      -run: node -version
      -run: npm install -g pnpm
      -run: pnpm -version
      -run: pnpm install
      -run: pnpm run lint
      -run: pnpm run build
