on: push

jobs:
  pnpm-build:
    name: pnpm build工作
    runs-on: ubuntu-latest
    steps:
      - name: 打印当前目录
        run: pwd
      - name: 检查node版本
        run: node -version
      - name: 安装pnpm
        run: npm install -g pnpm
      - name: 检查pnpm版本
        run: pnpm -version
      - name: 安装依赖pnpm包
        run: pnpm install
      - name: 检查pnpm包
        run: pnpm run lint
      - name: 构建项目
        run: pnpm run build
